apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jy94kimwc-go
  janus-idp.io/tekton: jy94kimwc-go
  backstage.io/kubernetes-id: jy94kimwc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jy94kimwc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
