apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jy94kimwc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jy94kimwc-go 
  name: jy94kimwc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jy94kimwc-go 
